// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateParticipant(ctx context.Context, db DBTX, arg CreateParticipantParams) (Participant, error)
}

var _ Querier = (*Queries)(nil)
