// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO participants (
    name, email, phone_number, problem_statement
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, name, email, phone_number, problem_statement, created_at
`

type CreateParticipantParams struct {
	Name             string `json:"name"`
	Email            string `json:"email"`
	PhoneNumber      string `json:"phone_number"`
	ProblemStatement string `json:"problem_statement"`
}

func (q *Queries) CreateParticipant(ctx context.Context, db DBTX, arg CreateParticipantParams) (Participant, error) {
	row := db.QueryRowContext(ctx, createParticipant,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.ProblemStatement,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.ProblemStatement,
		&i.CreatedAt,
	)
	return i, err
}
